apiVersion: v1
kind: Pod
spec:
  volumes:
    - name: "kaniko-secret"
      secret:
        secretName: regcred
        items:
          - key: ".dockerconfigjson"
            path: "config.json"
  containers:
    - name: "golang"
      image: golang:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"
      command:
        - "cat"
      tty: true
    - name: knaiko
      image: "gcr.io/kaniko-project/executor:debug"
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"
      command:
        - cat
      tty: true
      volumeMounts:
        - name: kaniko-secret
          mountPath: "/kaniko/.docker"
